### ISSUE TITLE
Assets tiles

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#455]
Design https://zpl.io/belryQD
![image](https://user-images.githubusercontent.com/47353570/105205307-c9222680-5b4d-11eb-890d-72beea74a516.png)

1) Remove "Assets" title
![image](https://user-images.githubusercontent.com/47353570/104940162-0786dc80-59ba-11eb-834a-906b84a84ad7.png)

2) Please remove icons from asset tile that shows active transactions
![image](https://user-images.githubusercontent.com/47353570/105172475-594d7500-5b28-11eb-8f15-36d61cc43a4f.png)

3) Increase tile height to 75px
![image](https://user-images.githubusercontent.com/47353570/105171510-f90a0380-5b26-11eb-9d75-94a41a69c992.png)

4) Increase triangle arrow size 
![image](https://user-images.githubusercontent.com/47353570/105201607-bad20b80-5b49-11eb-9680-87e8d5a28273.png)

5) Increase coin's icon size
![image](https://user-images.githubusercontent.com/47353570/105205405-e8b94f00-5b4d-11eb-9f00-bdc29c5759e1.png)

6) Place "Locked: [amount]" to asset tile. https://zpl.io/bAedOYp 
Click on arrow opens box with detailed info: amount (full amount, maturing, change, max privacy) and asset info
![image](https://user-images.githubusercontent.com/47353570/105171632-25258480-5b27-11eb-90fa-e06ee1bc165b.png)

6.1) In tile displays full amount (e.g. 290,987.9876 ASSETS) - in dropdown display only asset info https://zpl.io/25XKoXQ
![image](https://user-images.githubusercontent.com/47353570/105171899-79c8ff80-5b27-11eb-851f-c6abe6a0f9f7.png)

6.2) In tile displays short amount (e.g. 200M ASSETS) - in dropdown display full amount and  asset info https://zpl.io/aXlo5RM
![image](https://user-images.githubusercontent.com/47353570/105172038-aed55200-5b27-11eb-83c8-4d3069489b33.png)

6.3)  In tile full amount and locked - in dropdown display full amount, locked amount and asset info.
![image](https://user-images.githubusercontent.com/47353570/105172171-e217e100-5b27-11eb-8585-d7cffde6a240.png)

7) More detail connects only to Max privacy and opens dialog with info when locked amount will be unlocked https://zpl.io/VxEEkWE
![image](https://user-images.githubusercontent.com/47353570/105172246-ff4caf80-5b27-11eb-8ece-ca750ad738ec.png)

7) Add "verified" icon on verified assets https://zpl.io/belryQD
![image](https://user-images.githubusercontent.com/47353570/105205455-f5d63e00-5b4d-11eb-81f0-ea5709160780.png)

8) If asset has huge amount display it as [amount]M for millions or [amount]K for thousands.

**Comment by Roberrtt** [comment]
1.Change the background color of  tile for the beam
![Screenshot_406](https://user-images.githubusercontent.com/50007056/109923453-df381080-7ccf-11eb-9aee-5ee1a06e10cc.png)
2.The large asset description is not fully visible
![Screenshot_393](https://user-images.githubusercontent.com/50007056/109925981-7ce10f00-7cd3-11eb-8712-6768a0577424.png)
3.Change the name from "Smallest unit" to "Smallest unit name" in Asset Info
4.Change capital letter N to uppercase in Unit Name
![Screenshot_407](https://user-images.githubusercontent.com/50007056/109927776-c2064080-7cd5-11eb-96ea-ac8e218f52e8.png)
5. In Asset info no description of the items:
- Ratio
- Asset code

Need to discuss with @sasha-abramovich  because there are still fields that can be filled in but they aren't displayed
- OPT_SITE_URL= URL of the asset website
- OPT_PDF_URL= URL for the description paper
- OPT_FAVICON_URL= URL of the favicon
- OPT_LOGO_URL= URL of the logo in SVG vector format

6.Not done "Add "verified" icon on verified assets https://zpl.io/belryQD"
7.The name "Smallest unit" isn't taken from the meta date, written CA should be dragons
![Screenshot_398](https://user-images.githubusercontent.com/50007056/109929616-ba479b80-7cd7-11eb-8584-6807f336bb37.png)

**Comment by chapati** [comment]
5.' Asset code' is 'Asset name'. Asset code is too technical to display for users and actually it is not a code, it is name. We do not have any 'code' in asset metadata. Ratio is not displayed because it is not supported at the moment. It is added for the future.

OPT_SITE_URL is added as `Website`
OPT_PDF_URL is added as `Whitepaper`

These two would be used internally and not displayed
OPT_FAVICON_URL 
OPT_LOGO_URL

6. There is a separate task for verified assets

**Comment by KatsiarynaV** [comment]
Not fixed:
1. The "asset info" pop-up is displayed incorrectly

![28](https://user-images.githubusercontent.com/68267190/111457343-1d4e1f00-8729-11eb-9bc0-1c2c4c82c361.jpg)

2. Links don't open

![29](https://user-images.githubusercontent.com/68267190/111457378-2939e100-8729-11eb-851a-22b2dddd81ee.jpg)
 
build 6.0.10847.4027

**Comment by KatsiarynaV** [comment]
The "asset info" pop-up is still displayed incorrectly
![31](https://user-images.githubusercontent.com/68267190/111585546-88066580-87d0-11eb-81bf-39ebdb86e75c.jpg)
![33](https://user-images.githubusercontent.com/68267190/111585552-8a68bf80-87d0-11eb-8b9b-bbdb19647edf.jpg)
![34](https://user-images.githubusercontent.com/68267190/111585560-8d63b000-87d0-11eb-9d07-0e0b0c2e4b22.jpg)

**Comment by KatsiarynaV** [comment]
Checked
