### ISSUE TITLE
Rate Broadcasters compatibility

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#566]
While 5.x clients are active (unitl fork) need to run 2 broadcasters: old from 5.x & new 6.0. Need to setup that on servers.

**Comment by Denis-Asipenko** [comment]
We need to fix the issue the old broadcaster broadcasts the wrong rates for the new version of the wallet (6.0) before the fork happens. After the fork, the broadcaster will be updated.

On the mainnet RC where there hasn't been a fork yet, incorrect courses are displayed and errors are displayed in the logs due to the old broadcaster.
![image](https://user-images.githubusercontent.com/45556620/117168678-0d6dc580-add1-11eb-8a3e-3da82fe8db1f.png)
![image](https://user-images.githubusercontent.com/45556620/117168700-12cb1000-add1-11eb-864e-8434a33896c0.png)
![image](https://user-images.githubusercontent.com/45556620/117168958-51f96100-add1-11eb-8f98-963589f37f8f.png)


On the masternet where the fork has already, correct courses are displayed and errors aren't displayed in the logs because works new broadcaster.
![image](https://user-images.githubusercontent.com/45556620/117169692-fda2b100-add1-11eb-92a6-5b01eb536102.png)
![image](https://user-images.githubusercontent.com/45556620/117169726-06938280-add2-11eb-8bf3-efd301489d52.png)

**Comment by Sergei-Beam** [comment]
Rate Broadcasters returned unknown coin with unknown rate on **mainnet_6.0RC**
![image](https://user-images.githubusercontent.com/44496108/118177325-37f7f800-b43b-11eb-9121-6fc5708e37fc.png)

**Comment by Sergei-Beam** [comment]
Checked with @chapati 
Something wrong returned from my local database
Wallet.db to reproduce: 
[wallet.zip](https://github.com/BeamMW/beam-ui/files/6479285/wallet.zip)
pass: 2

**Comment by chapati** [comment]
This wallet.db has incorrectly rates when we had issues with compatibility. This should not happen on latest builds.

**Comment by Sergei-Beam** [comment]
checked on a clear wallet.db,can not reproduce
