### ISSUE TITLE
Asset register form on website

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#594]
Form itself: https://beamx.explorer.beam.mw/assets/create
Need to check if it produces correct CLI. 

1) Before it handled special symbols incorrectly (for example ") and the resulting command line did not worked.
2) Need to check if it works for linux & windows (different CLI rules, may be add switch)
3) Need to check if all fields from asset descriptor are supported. https://github.com/BeamMW/beam/wiki/Asset-Descriptor-v1.0
4) Need to check that only correct data is accepted (URL in url field)
5) Need to set some sane limit on some fields. For example not allow very long unit name & small unit name

**Comment by Denis-Asipenko** [comment]
1.The command line does not handle symbols such as  "  or  .  
If such symbols are not accepted for creating an asset,then you need to display errors if the user enters them when creating the asset
![image](https://user-images.githubusercontent.com/45556620/115529706-c98ca380-a29b-11eb-80d6-2bce71e17d22.png)
> 1. Before it handled special symbols incorrectly (for example ") and the resulting command line did not worked.

2.Need to either define the system or make a switch so that the command is generated for the system that the user uses. In this case, the command will not work because Windows does not use ". / " when entering the command.
![image](https://user-images.githubusercontent.com/45556620/115530137-2c7e3a80-a29c-11eb-9b4c-44146543d220.png)
> 2. Need to check if it works for linux & windows (different CLI rules, may be add switch)
3. Every description should be in English. need to display errors.
![image](https://user-images.githubusercontent.com/45556620/115534873-e677a580-a2a0-11eb-860b-dbd04eac0f95.png)

4. NTH_RATIO= cannot be an infinite number when creating an asset
![image](https://user-images.githubusercontent.com/45556620/115536658-b5987000-a2a2-11eb-8501-2c6c70ae8b76.png)


5.
![image](https://user-images.githubusercontent.com/45556620/115534748-c1833280-a2a0-11eb-97f0-fb353165e60c.png)
> 5. Need to set some sane limit on some fields. For example not allow very long unit name & small unit name

I also want to make a suggestion to add abbreviations in small font at the bottom to make it easier for users.
![image](https://user-images.githubusercontent.com/45556620/115539954-3d33ae00-a2a6-11eb-9d50-1f897ee8dfef.png)

**Comment by chapati** [comment]
Also

1. Command line should be correct for Win & Linux & Mac (shadow special symbols like ", space: \"blah\ blah). Rules of shadowing and allowed symbols can be different for Win & Linux. Should check.
2. N, SN, UN,  NTHUN  fields should allow only alphanumeric chars + space dot (.) comma (,) dash (-) and underscore (_)
3. OPT_SHORT_DESC <= 128 chars
4. OPT_LONG_DESC <= 1024 chars
5. Need to add all properties from https://github.com/BeamMW/beam/wiki/Asset-Descriptor-v1.0
6. OPT_COLOR should accept only valid hex color (#FFFFF0)
7. xxxx_URL fileds should be checked for valid urls
