### ISSUE TITLE
Max privacy transaction to yourself throws  "Failed to start wallet"

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#598]
When we send a transaction to our max privacy address, the wallet throws "Failed to start wallet"
In logs  sqlite error code=19, UNIQUE constraint failed: addresses.Address

Step:
- go to receive screen 
- copy max privacy address
- go to send screen
- paste address in the send field
- send some coins 

![Screenshot_6](https://user-images.githubusercontent.com/50007056/115253220-d80c7b00-a134-11eb-90a7-abecaff62e6d.png)

[beam_ui_21_04_19_17_26_27.log](https://github.com/BeamMW/beam-ui/files/6336837/beam_ui_21_04_19_17_26_27.log)

**Comment by chapati** [comment]
+ соmment is not loaded for maxprivacy address

**Comment by Roberrtt** [comment]
not fixed

https://user-images.githubusercontent.com/50007056/115371079-579c5780-a1d2-11eb-8a5b-1ed6fdf6df97.mp4

**Comment by KatsiarynaV** [comment]
1. The same behavior when sending second transaction to the regular/offline address to other wallet

Steps
1. Send regular or offline transaction from wallet B to wallet A
2. Try to send second regular or offline transaction to this address

![55](https://user-images.githubusercontent.com/68267190/115518179-91339800-a290-11eb-965d-571d8254eae7.jpg)
![56](https://user-images.githubusercontent.com/68267190/115518374-c04a0980-a290-11eb-80aa-6d2ba980522b.jpg)
![57](https://user-images.githubusercontent.com/68267190/115518376-c0e2a000-a290-11eb-9930-dfe22f997f03.jpg)

2. The wallet crashes:

Steps
1. In the wallet A copy max privacy address
2. In the wallet B send transaction to the wallet A
3. Try to send another transaction to this address from the wallet B

**Current behavior:** the wallet crashes. Error: unexpected identity in send::onGetAddressReturned

**Expected behavior:** the second transaction is failed

Reproduced only when sending max privacy transactions to other wallet
![gif08](https://user-images.githubusercontent.com/68267190/115515710-136e8d00-a28e-11eb-8e90-77991d2a5515.gif)

**Comment by KatsiarynaV** [comment]
Checked

**Comment by KatsiarynaV** [comment]
p. 2 (The wallet crashes) reproduced on build 6.0.11174.4192

**Comment by KatsiarynaV** [comment]
Not fixed

**Comment by KatsiarynaV** [comment]
Chekced on build 4.0.11183.4200
