### ISSUE TITLE
Cannot create a new permanent address

### ISSUE THREAD

**Issue by HumboldtK** [BeamMW/beam-ui#678]
Hello I followed the docs on the help page of beam's website and I have no options to choose a "never" expiring address... My old one was deleted. 

![26510d97d4da0b65d54cd15a4ca0d572](https://user-images.githubusercontent.com/73680593/124688304-64545180-de8b-11eb-9fd4-1e2c4a166c37.png)

**Comment by ya-shy** [comment]
Hello! Thank you for getting in touch. 

Basically, the logic behind the potentially expiring addresses at the moment is such: addresses (under 6.0 and later) are valid for 2 months. If you receive any transaction to this address within these 2 months it is extended for another 2 months automatically. Address issued today - transaction happened in a month - your wallet valid for 2 months since the transaction and so on.
So, as long as you are using the address, there should not be any issues. 

In addition, if you would click on 3 dots next to the wallet (under the Address book), then Edit address, you will see when your address is potentially expiring and if needed Extend it. 

Best regards!
