### ISSUE TITLE
[Restore] When the port is already in use the wallet doesn't return to the “Setup node connectivity” screen

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-ui#883]
Preconditions:
There are two UI wallets. Wallet A runs on the integrated Node, port 10005. The wallet B is a wallet that should be restored.
**Steps:**
1. Run wallet B, press “Restore wallet or created a new one” and tap the “proceed” button. 
2. Press “Restore wallet” and tap “I agree”.
3. Enter the Wallet B seed phrase and press the “next” button.
4. Press the “I understand” button on the “Do not simultaneously run two wallets initiated from the same seed phrase” pop-up.
5. Enter and confirm the Wallet B password on the “Create new password” screen and tap the “open my wallet” button.
6. The Wallet B is starting to restore. The “Connection error” pop-up appears.
7. Press the “Change settings” button.
![image](https://user-images.githubusercontent.com/83376495/146765319-19c8bd3d-72e5-4a9a-9afe-d8976b528060.png)
![image](https://user-images.githubusercontent.com/83376495/146765355-1abc8079-ade5-4b32-a5ec-d82427b6dee6.png)

**Expected result:** the “Setup node connectivity” screen is opened.
![image](https://user-images.githubusercontent.com/83376495/146773113-c3ed77ff-15e2-4774-8290-6390e5273607.png)
**Actual result:** the “Create new password” screen appears.
![image](https://user-images.githubusercontent.com/83376495/146765428-36937c71-390c-46d4-ac41-c7fcf991f126.png)

**Comment by KatsiarynaV** [comment]
1. When changing the node port and pressing the "start using your wallet" nothing happened, wallet doesn't start restoring process
![01](https://user-images.githubusercontent.com/68267190/154904845-eb32990d-c0c9-41b7-a5bb-3dedf3f49470.gif)

2. Since the restore is only available using integrated node disable the possibility to choose remote node connection

![01](https://user-images.githubusercontent.com/68267190/154905123-f62d90cc-2200-4b29-b071-c14dbd7157c1.jpg)

**Comment by KatsiarynaV** [comment]
Checked
